const gamesData = [
    {
        id: 1,
        nameAr: "لعبة الألغاز السحرية",
        nameEn: "Magic Puzzle Quest",
        image: "https://images.unsplash.com/photo-1538481143235-5d630a07cb0b?w=500&h=300&fit=crop",
        descriptionAr: "لعبة ألغاز مشوقة مع تحديات يومية وجوائز مجنونة تنتظرك!",
        descriptionEn: "Exciting puzzle game with daily challenges and amazing rewards waiting for you!",
        fullDescriptionAr: "انغمس في عالم الألغاز السحري حيث تحتاج إلى حل أكثر من 100 مستوى معقد. اجمع الألعاب والقوى الخاصة لتصبح بطل الألغاز.",
        fullDescriptionEn: "Dive into the magical puzzle world where you need to solve more than 100 complex levels. Collect power-ups and special abilities to become the Puzzle Master.",
        rating: 4.8,
        reviews: 2543,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 2,
        nameAr: "سباق السرعة الخارق",
        nameEn: "Thunder Racing",
        image: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=500&h=300&fit=crop",
        descriptionAr: "لعبة سباق بسرعة فائقة مع سيارات رائعة وتحديات مثيرة!",
        descriptionEn: "Super-fast racing game with amazing cars and thrilling challenges!",
        fullDescriptionAr: "قُد أسرع السيارات في العالم عبر مسارات خطيرة وممتعة. اجمع النقاط والجوائز لفتح سيارات جديدة ومسارات إضافية.",
        fullDescriptionEn: "Drive the world's fastest cars through dangerous and exciting tracks. Collect points and rewards to unlock new cars and additional tracks.",
        rating: 4.6,
        reviews: 1892,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 3,
        nameAr: "جزيرة الكنز المفقودة",
        nameEn: "Lost Treasure Island",
        image: "https://images.unsplash.com/photo-1552082692-882e087fc58a?w=500&h=300&fit=crop",
        descriptionAr: "اكتشف الكنز المخفي في جزيرة غامضة مليئة بالمغامرات!",
        descriptionEn: "Discover hidden treasure on a mysterious island full of adventures!",
        fullDescriptionAr: "استكشف جزيرة غامضة مليئة بالألغاز والعقبات. اجمع الخرائط والمفاتيح وافتح أقفال الكنز للحصول على جوائز مذهلة.",
        fullDescriptionEn: "Explore a mysterious island full of puzzles and obstacles. Collect maps and keys, unlock treasure chests to get amazing rewards.",
        rating: 4.7,
        reviews: 2156,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 4,
        nameAr: "محارب السماء الفضائي",
        nameEn: "Space Warrior Sky",
        image: "https://images.unsplash.com/photo-1533709752211-118fcf4e3312?w=500&h=300&fit=crop",
        descriptionAr: "لعبة أكشن فضائية بصرية مذهلة مع أعداء لا نهاية لهم!",
        descriptionEn: "Visually stunning space action game with endless enemies!",
        fullDescriptionAr: "قاتل الأعداء الفضائيين وحارب المحاربين المظلمين. اجمع القوى الخاصة وقم بتحديثات الأسلحة لتصبح أقوى محارب في الكون.",
        fullDescriptionEn: "Fight alien enemies and battle dark warriors. Collect power-ups and upgrade weapons to become the strongest warrior in the universe.",
        rating: 4.9,
        reviews: 3421,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 5,
        nameAr: "مدينة الأحلام الذهبية",
        nameEn: "Golden Dream City",
        image: "https://images.unsplash.com/photo-1552355291-bbee5972fb14?w=500&h=300&fit=crop",
        descriptionAr: "بناء مدينة حلمك الخاصة واجعلها من أجمل المدن!",
        descriptionEn: "Build your dream city and make it one of the most beautiful!",
        fullDescriptionAr: "شيّد مدينتك الخاصة بمبان رائعة وحدائق ساحرة. أدِر السكان، اجمع الموارد، وأنشئ إمبراطورية حقيقية.",
        fullDescriptionEn: "Build your own city with amazing buildings and magical gardens. Manage residents, collect resources, and create a true empire.",
        rating: 4.5,
        reviews: 1745,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 6,
        nameAr: "محقق اللغز الماهر",
        nameEn: "Mystery Detective Pro",
        image: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=500&h=300&fit=crop",
        descriptionAr: "حل الألغاز الجنائية واكتشف الحقائق المخفية في كل مستوى!",
        descriptionEn: "Solve criminal mysteries and uncover hidden truths in each level!",
        fullDescriptionAr: "كن محقق جنائي ماهر واحل قضايا معقدة. ابحث عن الأدلة، استجوب الشهود، وافتح القضايا الصعبة.",
        fullDescriptionEn: "Become an expert detective and solve complex cases. Search for evidence, interrogate witnesses, and crack difficult cases.",
        rating: 4.7,
        reviews: 2089,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 7,
        nameAr: "محارب الساموراي الشرقي",
        nameEn: "Eastern Samurai Warrior",
        image: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=500&h=300&fit=crop",
        descriptionAr: "لعبة قتالية آسيوية تقليدية مع حركات مميزة وخصوم قويين!",
        descriptionEn: "Traditional Asian combat game with unique moves and powerful enemies!",
        fullDescriptionAr: "تدرب على فنون الشرقية القديمة وصبح محارب ساموراي حقيقي. واجه زعماء أقوياء واكسب عديد التشريفات.",
        fullDescriptionEn: "Train in ancient Eastern arts and become a true samurai warrior. Face powerful bosses and win many honors.",
        rating: 4.8,
        reviews: 2634,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    },
    {
        id: 8,
        nameAr: "السحرة والمشعوذون",
        nameEn: "Wizards & Magicians",
        image: "https://images.unsplash.com/photo-1535371742066-581b8a0c9fd0?w=500&h=300&fit=crop",
        descriptionAr: "لعبة سحرية خيالية مع تعاويذ قوية وعوالم ساحرة!",
        descriptionEn: "Magical fantasy game with powerful spells and enchanted worlds!",
        fullDescriptionAr: "ادخل عالم السحر والخيال واختر سحرك الخاص. قاتل العفاريت واكسب قوى جديدة وافتح أسرار السحر القديم.",
        fullDescriptionEn: "Enter the world of magic and fantasy and choose your own spells. Fight demons and gain new powers to unlock ancient magic secrets.",
        rating: 4.6,
        reviews: 1956,
        androidLink: "https://play.google.com/store/apps",
        iphoneLink: "https://apps.apple.com"
    }
];